_BASE_: "../Base-RCNN-FPN.yaml"
MODEL:
  PIXEL_STD: [57.375, 57.120, 58.395]
  BACKBONE:
    NAME: "build_regnetx_fpn_backbone"
  WEIGHTS: "RegNetX-4.0GF_dds_8gpu.pyth"
  META_ARCHITECTURE: "SSRCNN"
#  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
  MASK_ON: False
  RESNETS:
    DEPTH: 50
  ROI_HEADS:
    NAME: "StandardROIHeadsSS"
    NUM_CLASSES: 10
  FPN:
    IN_FEATURES: [ "s1", "s2", "s3", "s4" ]
  SS:
    FEAT_LEVEL: "res4"
    NAME: ["build_cycle_energy_direct_add_all_head"]
    LOSS_SCALE: 0.0
    RATIO: 2.0
    COEF: 1.0
    FILTERING1: 0.4
    FILTERING2: 0.6
    ENERGY_WEIGHT: 0.05
DATASETS:
  TRAIN: ("bdd_tracking_2k_train",)
  TEST: ("nu_bdd_ood", )
SOLVER:
  IMS_PER_BATCH: 4
  WEIGHT_DECAY: 5e-5
#   IMS_PER_BATCH: 16
  BASE_LR: 0.02
#  STEPS: (31200, 41600,)
#  MAX_ITER: 45500
  STEPS: (36000, 48000,)
  MAX_ITER: 52500
  WARMUP_ITERS: 5000
INPUT:
  MIN_SIZE_TRAIN: (800,)
  RANDOM_FLIP: "none"
  CROP:
    ENABLED: True
SEED: 34112225
DATALOADER:
  SAMPLER_TRAIN: "PairTrainingMultiRandomSampler"
  PAIR_OFFSET_RANGE: 9
  SELCTED_NUMBER: 3
OUTPUT_DIR: "/nobackup/dataset/video/bdd/bdd100k/checkpoints/bdd_tracking_2k/daytime/energy_no_original_loss_direct_add_frame_9_revise_4to6_multi_random_regnet"