_BASE_: "/home/h1/s8993054/Flow_synthesis_BDD100kVID_imbatch_4_fg_sf_200_T_0pt010pt01_regnet/detection/configs/Base-RCNN-FPN.yaml"
MODEL:
  PIXEL_STD: [ 57.375, 57.120, 58.395 ]
  BACKBONE:
    NAME: "build_regnetx_fpn_backbone"
  META_ARCHITECTURE: "GeneralizedRCNNLogisticGMM"
  WEIGHTS: "/home/h1/s8993054/Flow_synthesis_BDD100kVID_imbatch_4_fg_sf_200_T_0pt010pt01_regnet/detection/configs/BDD100k/regnetx_detectron2.pth" #"regnetx_detectron2.pth"
  MASK_ON: False
  RESNETS:
    DEPTH: 50
  ROI_HEADS:
    NAME: "ROIHeadsLogisticGMMNew"
    NUM_CLASSES: 10
  FPN:
    IN_FEATURES: [ "s1", "s2", "s3", "s4" ]
INPUT:
  MIN_SIZE_TRAIN: (800,)
  MIN_SIZE_TEST: 800
DATASETS:
  TRAIN: ('bdd_tracking_2k_train',)
  TEST: ('bdd_tracking_2k_val', )
FFS:
  STARTING_ITER: 36000
  SAMPLE_NUMBER: 300
  BATCH_SIZE: 75
  SAMPLE_FROM: 200
SOLVER:
  IMS_PER_BATCH: 4
  BASE_LR: 0.02
  STEPS: (36000, 48000,)
  MAX_ITER: 52500
  WARMUP_ITERS: 5000
DATALOADER:
    NUM_WORKERS: 8  # Depends on the available memory