_BASE_: "/path/to/Flow-Feature-Synthesis/detection/configs/Base-RCNN-FPN.yaml"
MODEL:
  PIXEL_STD: [57.375, 57.120, 58.395]
  BACKBONE:
    NAME: "build_regnetx_fpn_backbone"
  META_ARCHITECTURE: "GeneralizedRCNNLogisticGMM"
  WEIGHTS: "/path/to/Flow-Feature-Synthesis/detection/configs/regnetx_detectron2.pth"

#  PROPOSAL_GENERATOR:
#    NAME: "RPNLogistic"
  FPN:
    IN_FEATURES: ["s1", "s2", "s3", "s4"]
  MASK_ON: False
  RESNETS:
    DEPTH: 50
  ROI_HEADS:
    NAME: "ROIHeadsLogisticGMMNew"
    NUM_CLASSES: 20
INPUT:
  MIN_SIZE_TRAIN: (480, 512, 544, 576, 608, 640, 672, 704, 736, 768, 800)
  MIN_SIZE_TEST: 800
DATASETS:
  TRAIN: ('voc_custom_train',)
  TEST: ('voc_custom_val',)
FFS:
  STARTING_ITER: 12000
  SAMPLE_NUMBER: 75
  BATCH_SIZE: 75
  SAMPLE_FROM: 200
SOLVER:
  IMS_PER_BATCH: 16
  BASE_LR: 0.02
  WEIGHT_DECAY: 5e-5
  STEPS: (12000, 16000)
  MAX_ITER: 24000  
  WARMUP_ITERS: 100
DATALOADER:
    NUM_WORKERS: 8  # Depends on the available memory