_BASE_: "/home/h1/s8993054/Flow_synthesis_BDD100kVID_imbatch_4_fg_sf_200_T_11_resnet/detection/configs/Base-RCNN-FPN.yaml"
MODEL:
  META_ARCHITECTURE: "GeneralizedRCNNLogisticGMM"
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
  MASK_ON: False
  RESNETS:
    DEPTH: 50
  ROI_HEADS:
    NAME: "ROIHeadsLogisticGMMNew"
    NUM_CLASSES: 10
INPUT:
  MIN_SIZE_TRAIN: (800,)
  MIN_SIZE_TEST: 800
DATASETS:
  TRAIN: ('bdd_tracking_2k_train',)
  TEST: ('bdd_tracking_2k_val', )
FFS:
  STARTING_ITER: 36000
  SAMPLE_NUMBER: 300
  BATCH_SIZE: 75
  SAMPLE_FROM: 200
SOLVER:
  IMS_PER_BATCH: 4
  BASE_LR: 0.02
  STEPS: (36000, 48000,)
  MAX_ITER: 52500
  WARMUP_ITERS: 5000
DATALOADER:
    NUM_WORKERS: 8  # Depends on the available memory