MODEL:
    META_ARCHITECTURE: "Detr"

    MASK_ON: False

    RESNETS:
        DEPTH: 50
        STRIDE_IN_1X1: False
        OUT_FEATURES: ["res2", "res3", "res4", "res5"]

    DETR:
        GIOU_WEIGHT: 2.0
        L1_WEIGHT: 5.0
        NUM_OBJECT_QUERIES: 100

INPUT:
    MIN_SIZE_TRAIN: (480, 512, 544, 576, 608, 640, 672, 704, 736, 768, 800)
    CROP:
        ENABLED: True
        TYPE: "absolute_range"
        SIZE: (384, 600)
    FORMAT: "RGB"

SOLVER:
    CHECKPOINT_PERIOD: 30000

VERSION: 2
