_BASE_: "/path/to/Flow-Feature-Synthesis/detection/configs/Base-RCNN-FPN.yaml"
MODEL:
  PIXEL_STD: [ 57.375, 57.120, 58.395 ]
  BACKBONE:
    NAME: "build_regnetx_fpn_backbone"
  WEIGHTS: "/path/to/s8993054/Flow-Feature-Synthesis/detection/configs/regnetx_detectron2.pth" #"regnetx_detectron2.pth"
  META_ARCHITECTURE: "GeneralizedRCNNLogisticGMM"
  MASK_ON: False
  RESNETS:
    DEPTH: 50
  ROI_HEADS:
    NAME: "ROIHeadsLogisticGMMNew"
    NUM_CLASSES: 40
  FPN:
    IN_FEATURES: [ "s1", "s2", "s3", "s4" ]
INPUT:
  MIN_SIZE_TRAIN: (800,)
  MIN_SIZE_TEST: 800
DATASETS:
  TRAIN: ('vis21_train',)
  TEST: ('vis21_val', )
FFS:
  STARTING_ITER: 30000
  SAMPLE_NUMBER: 300
  BATCH_SIZE: 75
  SAMPLE_FROM: 200
SOLVER:
  IMS_PER_BATCH: 16
  BASE_LR: 0.02
  WEIGHT_DECAY: 5e-5
  STEPS: (30000, 45000,)
  MAX_ITER: 600  # 60000
  WARMUP_ITERS: 1000
DATALOADER:
    NUM_WORKERS: 8  # Depends on the available memory